MODULE rates

! pointers
DOUBLE PRECISION, DIMENSION(:), POINTER ::  Lcont => NULL()
DOUBLE PRECISION, DIMENSION(:), POINTER :: Lcool_excit => NULL()
DOUBLE PRECISION, DIMENSION(:), POINTER :: Lcool_ff => NULL()

END MODULE rates
