! reads 1D model generated by the PoWR code
!
!
! 1. radius / R_*
! 2. radial velocity / km * s^(-1)
! 3. total numerical mass density
! 4. temperature / K
!
! INPUT: NONE
! OUTPUT: NONE
!
SUBROUTINE read_1D_PoWR()

USE types
USE constants

IMPLICIT NONE    


INTEGER                                   :: ind_I, ind_J, numbions, atom_number
! for reading from files
INTEGER                                   :: ios
INTEGER, PARAMETER                        :: maxrows = 6000000
DOUBLE PRECISION                          :: r, velo, dens, temp
! DOUBLE PRECISION, DIMENSION(n_elements)   :: massfrac
! variables which are not needed in the code
!DOUBLE PRECISION                          :: delta_r, delta, delta2, tot_nd, tot_md
! (2) PoWR model
CHARACTER(filename_length)                             :: line
DOUBLE PRECISION, PARAMETER                :: meanAtMass = 1.33

write(99,*) 'we will read the TESTCASE from the PoWR code...'
R_star = 20.066 * const_Rsun
T_eff = 37000
add_mg = 2
write(*,*) 'read_1D_PoWR: powrfile = ', inputmodelFile
n_modelgrid = 0
OPEN(UNIT=11, STATUS="old", FILE=inputmodelFile)
DO
 read(11, *, IOSTAT=ios) line
 IF (ios /= 0) EXIT
 n_modelgrid = n_modelgrid + 1
END DO
ALLOCATE (model_grid(n_modelgrid + add_mg))
write(99,*) 'read_1D_PoWR: n_modelgrid = ', n_modelgrid
REWIND(11)
DO ind_I=1,n_modelgrid
 READ(11,*) r, velo, dens, temp
 ! write(*,*) 'read_1D_PoWR: ind_I = ', ind_I, ' r = ', r, ' velo = ', velo, ' dens = ', dens, ' temp = ', temp
 model_grid(ind_I)%rwind = r * R_star
 model_grid(ind_I)%vel = velo * 1.E5
 model_grid(ind_I)%rho = dens * meanAtMass * const_mp_g
 model_grid(ind_I)%T = temp 
 model_grid(ind_I)%J = 0.D0 
 model_grid(ind_I)%assoc_cells = 0
 ! print*, 'read_1D_PoWR: testing model grid...'
 ! print*, 'read_1D_PoWR: ', I, model_grid(I)%rwind, model_grid(I)%vel, &
 !  model_grid(I)%rho, model_grid(I)%T, model_grid(I)%J, &
 !  model_grid(I)%assoc_cells
 !IF (ind_I /= 1) print*, 'delta r: ', model_grid(I)%rwind - model_grid(I-1)%rwind
 ALLOCATE (model_grid(ind_I)%grid_comp(n_elements))
 DO ind_J = 1, n_elements      
  numbions = elements(ind_J)%nions
  ALLOCATE (model_grid(ind_I)%grid_comp(ind_J)%grid_ion(numbions))
  atom_number = elements(ind_J)%atom_number
  model_grid(ind_I)%grid_comp(ind_J)%abund = elements(ind_J)%abundance
  !Calculate total number density for included species
  !tot_nd = model_grid(ind_I)%grid_comp(ind_J)%abund / elements(ind_J)%atom_mass 
  !model_grid(ind_I)%grid_comp(ind_J)%numb_den = tot_nd
 END DO
END DO
R_inf  = model_grid(1)%rwind
write(*,*) 'read_1D_PoWR: R_inf = ', R_inf / R_star
V_inf  = model_grid(1)%vel
outerspace_index = n_modelgrid + 1
photosphere_index = n_modelgrid + 2
! write(99,*) 'read_1D_PoWR: R_star = ', R_star, ' R_inf = ', R_inf
! Dummy cell to associate to propagation grid cells which have no
! representation on the model grid. All cells out of model grid
! set to 0 and associate to n_modelgrid. Other cells will obtainde
! particular values with memory
model_grid(outerspace_index)%rwind = 0.D0
model_grid(outerspace_index)%vel   = 0.D0
model_grid(outerspace_index)%rho   = 0.D0     
model_grid(photosphere_index)%rwind = 0.D0
model_grid(photosphere_index)%vel   = 0.D0
model_grid(photosphere_index)%rho   = 0.D0     
CLOSE(11)
! STOP 'read_1D_PoWR: testing...'

END SUBROUTINE read_1D_PoWR
